# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: SauceDemo CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run tests
        run: mvn clean test

        continue-on-error: true

      - name: Get Allure history
        uses: actions/checkout@v4
        if: always() # Выполнять шаг всегда, даже если тесты упали
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@v1.9
        if: always() # Выполнять шаг всегда
        with:
          allure_results: target/allure-results
          allure_history: allure-history
          keep_reports: 20 # Ограничение истории до 20 последних запусков

      - name: Copy index.html to root
        if: always()
        run: |
          if [ -d "gh-pages/allure-history/${{ github.run_number }}" ]; then
            cp -r gh-pages/allure-history/${{ github.run_number }}/* gh-pages/
            echo "Файлы отчета успешно скопированы в корень"
          else
            echo "Папка с отчетом не найдена"
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: always() # Выполнять шаг всегда, чтобы увидеть отчет по упавшим тестам
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-history

   
